from django.urls import path
from .views import *
urlpatterns = [
    path('home/',index,name='home'),
    path('mens/',mens,name='mens'),
    path('', loginpage, name='login'),
    path('womens/',womens,name='womens'),
    path('children/',childrens,name='children'),
    path('', loginpage, name='login'),
    path('login/', loginpage, name='login'),
    path('main/', main123, name='home'),
    path('mens/mens shirt/', mensshirt, name='mens_shirt'),
    path('mens/mens pant/', menspant, name='mens_pant'),
    path('mens/mens Tshirt/', menstshirt, name='mens_Tshirt'),
    path('mens shirt/', mensshirt, name='mensshirt'),
    path('mens pant/', menspant, name='menspant'),
    path('mens Tshirt/', menstshirt, name='mensTshirt'),
    path('womens/women Kurta/', womenk, name='women_Kurta'),
    path('womens/women saree/', women, name='women_saree'),
    path('women Kurta/', womenk, name='womenKurta'),
    path('women saree/', women, name='womensaree'),
    path('children/Kids pant/', kidpant, name='kids_pant'),
    path('Kids pant/', kidpant, name='kidspant'),
    path('children/Kids shirt/', kidshirt, name='kids_shirt'),
    path('Kids shirt/', kidshirt, name='kidsshirt'),
    path('children/Kids tshirt/', kidtshirt, name='kids_tshirt'),
    path('Kids tshirt/', kidtshirt, name='kidstshirt'),
]